Lesson06 - Entity framework/Lesson06 - Entity framework/Models/VhhBook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lesson06___Entity_framework.Models
{
    public class PvvBook
    {
        [Key]
        public int PvvId { get; set; }
        public string PvvBookId { get; set; }
        public string PvvTitle { get; set;}
        public string PvvAuthor { get;set; }
        public int PvvYear { get;set; }
        public string PvvPulisher { get; set; }  
        public string PvvPicture { get; set; }
        public int PvvCategoryId { get; set; }
        public virtual PvvCategory PvvCategory { get; set; }



    }
}

Lesson06 - Entity framework/Lesson06 - Entity framework/Models/VhhBookStore.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Lesson06___Entity_framework.Models
{
    public class PvvBookStore:DbContext
    {
        public PvvBookStore():base() { }

        public DbSet<PvvCategory> PvvCategories { get; set; }  
        public DbSet<PvvBook> PvvBooks { get; set; }
    }
}

Lesson06 - Entity framework/Lesson06 - Entity framework/Models/VhhCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lesson06___Entity_framework.Models
{
    public class PvvCategory
    {
        [Key]
        public int PvvId { get; set; }
        public string PvvCategoryName { get; set;}
        public virtual ICollection<PvvBook> PvvBooks { get; set; }
    }
}

Lesson06 - Entity framework/Lesson06 - Entity framework/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lesson06___Entity_framework.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lesson06 - Entity framework/Lesson06 - Entity framework/Controllers/VhhBooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lesson06___Entity_framework.Models;

namespace Lesson06___Entity_framework.Controllers
{
    public class PvvBooksController : Controller
    {
        private PvvBookStore db = new PvvBookStore();

        // GET: PvvBooks
        public ActionResult Index()
        {
            return View(db.PvvBooks.ToList());
        }

        // GET: PvvBooks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PvvBook pvvBook = db.PvvBooks.Find(id);
            if (pvvBook == null)
            {
                return HttpNotFound();
            }
            return View(pvvBook);
        }

        // GET: PvvBooks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PvvBooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PvvId,PvvBookId,PvvTitle,PvvAuthor,PvvYear,PvvPulisher,PvvPicture,PvvCategoryId")] PvvBook pvvBook)
        {
            if (ModelState.IsValid)
            {
                db.PvvBooks.Add(pvvBook);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pvvBook);
        }

        // GET: PvvBooks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PvvBook pvvBook = db.PvvBooks.Find(id);
            if (pvvBook == null)
            {
                return HttpNotFound();
            }
            return View(pvvBook);
        }

        // POST: PvvBooks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PvvId,PvvBookId,PvvTitle,PvvAuthor,PvvYear,PvvPulisher,PvvPicture,PvvCategoryId")] PvvBook pvvBook)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pvvBook).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pvvBook);
        }

        // GET: PvvBooks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PvvBook pvvBook = db.PvvBooks.Find(id);
            if (pvvBook == null)
            {
                return HttpNotFound();
            }
            return View(pvvBook);
        }

        // POST: PvvBooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PvvBook pvvBook = db.PvvBooks.Find(id);
            db.PvvBooks.Remove(pvvBook);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lesson06 - Entity framework/Lesson06 - Entity framework/Controllers/VhhCategoriesController.cs
using Lesson06___Entity_framework.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lesson06___Entity_framework.Controllers
{
    public class PvvCategoriesController : Controller

    {
        private static PvvBookStore pvvDb;
        public PvvCategoriesController()
        {
            pvvDb = new PvvBookStore();
        }
        // GET: PvvCategories
        public ActionResult PvvIndex()
        {
           // PvvBookStore pvvDb = new PvvBookStore();
            var pvvCategories =pvvDb.PvvCategories.ToList();
            return View(pvvCategories);
        }
        public ActionResult PvvCreate()
        {
            var pvvCategory = new PvvBookStore();
            return View(pvvCategory);
        }
        [HttpPost]
        public ActionResult PvvCreate(PvvCategory pvvCategory)
        {
           pvvDb.PvvCategories.Add(pvvCategory);
            pvvDb.SaveChanges();
            return RedirectToAction("PvvIndex");
        }
    }
}

Lesson06 - Entity framework/Lesson06 - Entity framework/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Lesson06 - Entity framework/Lesson06 - Entity framework/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Lesson06 - Entity framework/Lesson06 - Entity framework/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Lesson06 - Entity framework/Lesson06 - Entity framework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - phan viet vuong</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("phan viet vuong", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Pvv:Category", "PvvIndex", "PvvCategories", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Pvv:Book", "Index", "PvvBook", new { area = "" }, new { @class = "nav-link" })</li>


                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - phan viet vuong</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Lesson06 - Entity framework/Lesson06 - Entity framework/Views/VhhBooks/Create.cshtml
@model Lesson06___Entity_framework.Models.PvvBook

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PvvBook</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PvvBookId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvBookId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvBookId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PvvTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PvvAuthor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvAuthor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvAuthor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PvvYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PvvPulisher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvPulisher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvPulisher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PvvPicture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvPicture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvPicture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PvvCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvCategoryId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lesson06 - Entity framework/Lesson06 - Entity framework/Views/VhhBooks/Delete.cshtml
@model Lesson06___Entity_framework.Models.PvvBook

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PvvBook</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PvvBookId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PvvBookId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PvvTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PvvTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PvvAuthor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PvvAuthor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PvvYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PvvYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PvvPulisher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PvvPulisher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PvvPicture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PvvPicture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PvvCategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PvvCategoryId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Lesson06 - Entity framework/Lesson06 - Entity framework/Views/VhhBooks/Details.cshtml
@model Lesson06___Entity_framework.Models.PvvBook

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PvvBook</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PvvBookId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PvvBookId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PvvTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PvvTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PvvAuthor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PvvAuthor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PvvYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PvvYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PvvPulisher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PvvPulisher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PvvPicture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PvvPicture)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PvvCategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PvvCategoryId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PvvId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Lesson06 - Entity framework/Lesson06 - Entity framework/Views/VhhBooks/Edit.cshtml
@model Lesson06___Entity_framework.Models.PvvBook

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PvvBook</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PvvId)

        <div class="form-group">
            @Html.LabelFor(model => model.PvvBookId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvBookId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvBookId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PvvTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PvvAuthor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvAuthor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvAuthor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PvvYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PvvPulisher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvPulisher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvPulisher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PvvPicture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvPicture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvPicture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PvvCategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvCategoryId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lesson06 - Entity framework/Lesson06 - Entity framework/Views/VhhBooks/Index.cshtml
@model IEnumerable<Lesson06___Entity_framework.Models.PvvBook>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PvvBookId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PvvTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PvvAuthor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PvvYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PvvPulisher)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PvvPicture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PvvCategoryId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PvvBookId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PvvTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PvvAuthor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PvvYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PvvPulisher)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PvvPicture)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PvvCategoryId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PvvId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PvvId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PvvId })
        </td>
    </tr>
}

</table>

Lesson06 - Entity framework/Lesson06 - Entity framework/Views/VhhCategories/VhhCreate.cshtml
@model Lesson06___Entity_framework.Models.PvvCategory

@{
    ViewBag.Title = "PvvCreate";
}

<h2>PvvCreate</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PvvCategory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PvvCategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PvvCategoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PvvCategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lesson06 - Entity framework/Lesson06 - Entity framework/Views/VhhCategories/VhhIndex.cshtml
@model IEnumerable<Lesson06___Entity_framework.Models.PvvCategory>

@{
    ViewBag.Title = "PvvIndex";
}

<h2>PvvIndex</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PvvCategoryName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PvvCategoryName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PvvId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PvvId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PvvId })
        </td>
    </tr>
}

</table>